FROM openshift/origin-release:golang-1.10 AS builder
COPY . /go/src/github.com/kubernetes-incubator/external-storage
RUN cd /go/src/github.com/kubernetes-incubator/external-storage/snapshot && \
    make controller

FROM openshift/origin-base
COPY --from=builder /go/src/github.com/kubernetes-incubator/external-storage/snapshot/_output/bin/snapshot-controller /usr/bin

ENTRYPOINT ["/usr/bin/snapshot-controller"]
